spring.application.name=payment-service
server.port=3004

spring.data.mongodb.uri=mongodb+srv://movie_ticket_payment:movieticketpayment@movieticketpayment.s6ictf1.mongodb.net/paymentdb?retryWrites=true&w=majority&appName=MovieTicketPayment